lastest

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,8 +46,26 @@ jobs:
             --restart always \
             ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
             echo "New container started with correct port 3000:8000."
-            sudo sed -i 's/127.0.0.1:8000/127.0.0.1:3000/g' /etc/nginx/conf.d/devops-app.conf || true
-            sudo systemctl reload nginx
-            echo "Nginx reloaded, pointing to port 3000."
+            sudo tee /etc/nginx/conf.d/devops-app.conf > /dev/null <<'EOF'
+            server{
+             listen 80;
+             server_name _;
+
+             location / {
+                proxy_pass http://127.0.0.1:3000;
+                proxy_set_header Host $host;
+                proxy_set_header X-Real-IP $remote_addr;
+                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
+                proxy_set_header X-Forwarded-Proto $scheme;
+                }
+            }
+            EOF
+            if sudo nginx -t; then
+            sudo systemctl restart nginx
+              echo "Nginx reloaded and pointing to port 3000."
+            else
+              echo "Nginx configuration error! Please check logs."
+            exit 1
+            fi
             sudo docker ps
             echo "--- Deployment Complete ---"       
